---
kind: pipeline
type: docker
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags: 1.0.0-linux-arm64
    repo: linutux/gandi-dns
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
type: docker
name: default-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags: 1.0.0-linux-amd64
    repo: linutux/gandi-dns
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push
---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: linutux/gandi-dns:1.0.0
    template: linutux/gandi-dns:1.0.0-OS-ARCH
    platforms:
      - linux/arm64
      - linux/amd64

- name: manifest-latest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: linutux/gandi-dns:latest
    template: linutux/gandi-dns:1.0.0-OS-ARCH
    platforms:
      - linux/arm64
      - linux/amd64

depends_on:
- default-arm64
- default-amd64
---
kind: signature
hmac: 39e487bd91e1b58dc86ef2be57898961321bf65117e87d9fbc55554d3348493c

...
